import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

export const metadata = { title: "Terms of Service - CarMogger" };

const cardStyle: React.CSSProperties = { borderRadius: 12, background: "#111114", border: "1px solid rgba(255,255,255,0.07)", padding: 32 };

export default function TermsPage() {
  const sections = [
    { title: "1. Acceptance of Terms", body: 'By accessing or using CarMogger ("carmogger.com"), you agree to be bound by these Terms of Service. If you do not agree, do not use the platform. CarMogger is operated from New South Wales, Australia.' },
    { title: "2. Description of Service", body: "CarMogger provides an AI-powered car rating platform where users can upload images of their vehicles to receive automated Mog Scores across five categories: Aura, Larp, Money, Demand, and Hype. Users can participate in leaderboards, earn XP, progress through leagues, and embed their scores on external platforms." },
    { title: "3. User Accounts", body: "You may need to create an account to access certain features. You are responsible for maintaining the confidentiality of your credentials. You must provide accurate information and be at least 13 years old. We reserve the right to suspend or terminate accounts that violate these terms." },
    { title: "4. User Content", body: "By uploading images to CarMogger, you grant us a non-exclusive, worldwide, royalty-free license to use, display, and process those images for the purpose of providing our services, including AI analysis and displaying rated cars on leaderboards and profiles. You retain ownership of your images. You represent that you have the right to upload all content you submit and that it does not infringe on any third party rights." },
    { title: "5. AI Scoring", body: "Car ratings are generated by artificial intelligence and are provided for entertainment purposes. Scores are subjective assessments and do not represent official valuations, appraisals, or expert opinions. CarMogger makes no guarantees about the accuracy of AI-generated scores, vehicle identification, or analysis." },
    { title: "6. Leagues, XP, and Leaderboards", body: "The league system, XP points, levels, and leaderboard positions are gamification features with no monetary value. We reserve the right to modify the league structure, XP earning rates, seasonal resets, and leaderboard algorithms at any time. XP and league positions are not transferable." },
    { title: "7. Prohibited Conduct", body: "You agree not to: upload images you do not own or have rights to; use bots or automated systems to manipulate views, scores, or XP; upload inappropriate, offensive, or illegal content; attempt to reverse-engineer the AI scoring system; create multiple accounts to circumvent restrictions; harass other users." },
    { title: "8. Paid Features", body: "Certain premium features may require payment. All payments are processed through Stripe. Subscriptions auto-renew unless cancelled. Refunds are handled on a case-by-case basis. Prices are in AUD unless otherwise stated." },
    { title: "9. Intellectual Property", body: "The CarMogger name, logo, scoring system, and platform design are proprietary. You may not reproduce, distribute, or create derivative works without written permission. The embed feature is provided for personal use on social media profiles and personal websites only." },
    { title: "10. Limitation of Liability", body: 'CarMogger is provided "as is" without warranties of any kind. To the maximum extent permitted by law, we shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the platform. Our total liability shall not exceed the amount you paid us in the 12 months preceding the claim.' },
    { title: "11. Privacy", body: "Your use of CarMogger is also governed by our Privacy Policy. By using the platform, you consent to the collection and use of information as described therein." },
    { title: "12. Modifications", body: "We reserve the right to modify these terms at any time. Changes will be posted on this page with an updated date. Continued use after changes constitutes acceptance of the new terms." },
    { title: "13. Governing Law", body: "These terms are governed by the laws of New South Wales, Australia. Any disputes shall be subject to the exclusive jurisdiction of the courts of New South Wales." },
    { title: "14. Contact", body: "For questions about these terms, contact us at hello@carmogger.com." },
  ];

  return (
    <div style={{ width: "100%", minHeight: "100vh" }}>
      <Navbar />

      <section style={{ width: "100%", paddingTop: 120, paddingBottom: 40, position: "relative", overflow: "hidden" }}>
        <div style={{ position: "absolute", top: 0, left: "50%", transform: "translateX(-50%)", width: 600, height: 300, background: "radial-gradient(ellipse, rgba(59,130,246,0.08) 0%, transparent 70%)", pointerEvents: "none" }} />
        <div className="ctr" style={{ textAlign: "center", position: "relative" }}>
          <p className="fade-up d1 mono" style={{ fontSize: 11, color: "#3b82f6", textTransform: "uppercase", letterSpacing: "0.12em", marginBottom: 16 }}>[ Legal ]</p>
          <h1 className="fade-up d2" style={{ fontSize: "clamp(32px, 5vw, 48px)", fontWeight: 800, color: "white", lineHeight: 1.05 }}>
            Terms of Service
          </h1>
          <p className="fade-up d3 mono" style={{ marginTop: 16, fontSize: 12, color: "#52525b" }}>Last updated: 27 March 2026</p>
        </div>
      </section>

      <section style={{ width: "100%", paddingBottom: 80 }}>
        <div className="ctr">
          <div style={{ ...cardStyle, maxWidth: 800, marginLeft: "auto", marginRight: "auto" }}>
            <div style={{ display: "flex", flexDirection: "column", gap: 32 }}>
              {sections.map((s) => (
                <div key={s.title}>
                  <h2 style={{ fontSize: 16, fontWeight: 700, color: "white", marginBottom: 12 }}>{s.title}</h2>
                  <p style={{ fontSize: 13, color: "#a1a1aa", lineHeight: 1.7 }}>{s.body}</p>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      <Footer />
    </div>
  );
}
