import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

export const metadata = { title: "Terms of Service - CarMogger" };

export default function TermsPage() {
  return (
    <>
      <Navbar />
      <main className="relative z-10 min-h-screen pt-28 pb-16 px-4">
        <div className="max-w-3xl mx-auto prose-invert">
          <h1 className="text-3xl sm:text-4xl font-black mb-2">Terms of Service</h1>
          <p className="text-sm text-[var(--grey-500)] mb-10">Last updated: 27 March 2026</p>

          <div className="space-y-8 text-[var(--grey-300)] text-sm leading-relaxed">
            <section>
              <h2 className="text-lg font-bold text-white mb-3">1. Acceptance of Terms</h2>
              <p>By accessing or using CarMogger (&quot;carmogger.com&quot;), you agree to be bound by these Terms of Service. If you do not agree, do not use the platform. CarMogger is operated from New South Wales, Australia.</p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-white mb-3">2. Description of Service</h2>
              <p>CarMogger provides an AI-powered car rating platform where users can upload images of their vehicles to receive automated scores across five categories: Aura, Larp, Money, Demand, and Hype. Users can participate in leaderboards, earn XP, progress through leagues, and embed their scores on external platforms.</p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-white mb-3">3. User Accounts</h2>
              <p>You may need to create an account to access certain features. You are responsible for maintaining the confidentiality of your credentials. You must provide accurate information and be at least 13 years old. We reserve the right to suspend or terminate accounts that violate these terms.</p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-white mb-3">4. User Content</h2>
              <p>By uploading images to CarMogger, you grant us a non-exclusive, worldwide, royalty-free license to use, display, and process those images for the purpose of providing our services, including AI analysis and displaying rated cars on leaderboards and profiles. You retain ownership of your images. You represent that you have the right to upload all content you submit and that it does not infringe on any third party rights.</p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-white mb-3">5. AI Scoring</h2>
              <p>Car ratings are generated by artificial intelligence and are provided for entertainment purposes. Scores are subjective assessments and do not represent official valuations, appraisals, or expert opinions. CarMogger makes no guarantees about the accuracy of AI-generated scores, vehicle identification, or analysis.</p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-white mb-3">6. Leagues, XP, and Leaderboards</h2>
              <p>The league system, XP points, levels, and leaderboard positions are gamification features with no monetary value. We reserve the right to modify the league structure, XP earning rates, seasonal resets, and leaderboard algorithms at any time. XP and league positions are not transferable.</p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-white mb-3">7. Prohibited Conduct</h2>
              <p>You agree not to: upload images you do not own or have rights to; use bots or automated systems to manipulate views, scores, or XP; upload inappropriate, offensive, or illegal content; attempt to reverse-engineer the AI scoring system; create multiple accounts to circumvent restrictions; harass other users.</p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-white mb-3">8. Paid Features</h2>
              <p>Certain premium features may require payment. All payments are processed through Stripe. Subscriptions auto-renew unless cancelled. Refunds are handled on a case-by-case basis. Prices are in AUD unless otherwise stated.</p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-white mb-3">9. Intellectual Property</h2>
              <p>The CarMogger name, logo, scoring system, and platform design are proprietary. You may not reproduce, distribute, or create derivative works without written permission. The embed feature is provided for personal use on social media profiles and personal websites only.</p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-white mb-3">10. Limitation of Liability</h2>
              <p>CarMogger is provided &quot;as is&quot; without warranties of any kind. To the maximum extent permitted by law, we shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the platform. Our total liability shall not exceed the amount you paid us in the 12 months preceding the claim.</p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-white mb-3">11. Privacy</h2>
              <p>Your use of CarMogger is also governed by our Privacy Policy. By using the platform, you consent to the collection and use of information as described therein.</p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-white mb-3">12. Modifications</h2>
              <p>We reserve the right to modify these terms at any time. Changes will be posted on this page with an updated date. Continued use after changes constitutes acceptance of the new terms.</p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-white mb-3">13. Governing Law</h2>
              <p>These terms are governed by the laws of New South Wales, Australia. Any disputes shall be subject to the exclusive jurisdiction of the courts of New South Wales.</p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-white mb-3">14. Contact</h2>
              <p>For questions about these terms, contact us at hello@carmogger.com.</p>
            </section>
          </div>
        </div>
      </main>
      <Footer />
    </>
  );
}
